--- !DirTarget
directoryToSaveModels: manipulation/
directoryToExportModels: output/
pathToTemplateModelsDirectory: config/
pathToProfile: config/smarty.profile.uml
pathToProfileConcern: config/concerns.profile.uml
pathToProfileRelationships: config/relationships.profile.uml
pathToProfilePatterns: config/patterns.profile.uml