--- !DirTarget
directoryToSaveModels: manipulation/
directoryToExportModels: output/
pathToTemplateModelsDirectory: ServiceAndSupportSystem/Papyrus/
pathToProfile: ServiceAndSupportSystem/Papyrus/smarty.profile.uml
pathToProfileConcern: ServiceAndSupportSystem/Papyrus/concerns.profile.uml
pathToProfileRelationships: ServiceAndSupportSystem/Papyrus/relationships.profile.uml
pathToProfilePatterns: ServiceAndSupportSystem/Papyrus/patterns.profile.uml