--- !DirTarget
directoryToSaveModels: manipulation/
directoryToExportModels: output/
pathToTemplateModelsDirectory: MicrowaveOvenSoftware/Papyrus/
pathToProfile: MicrowaveOvenSoftware/Papyrus/smarty.profile.uml
pathToProfileConcern: MicrowaveOvenSoftware/Papyrus/concerns.profile.uml
pathToProfileRelationships: MicrowaveOvenSoftware/Papyrus/relationships.profile.uml
pathToProfilePatterns: MicrowaveOvenSoftware/Papyrus/patterns.profile.uml