--- !DirTarget
pathToTemplateModelsDirectory: config/
directoryToSaveModels: manipulation/
directoryToExportModels: output/
pathToProfile: /home/giovaniguizzo/NetBeansProjects/OPLA-Patterns/AGMFinal/smarty.profile.uml
pathToProfileConcern: /home/giovaniguizzo/NetBeansProjects/OPLA-Patterns/AGMFinal/perfilConcerns.profile.uml
