--- !DirTarget
directoryToSaveModels: test/br/ufpr/inf/opla/patterns/resources/manipulation/
directoryToExportModels: test/br/ufpr/inf/opla/patterns/resources/output/
pathToProfile: config/smarty.profile.uml
pathToProfileConcern: config/perfilConcerns.profile.uml