--- !DirTarget
pathToTemplateModelsDirectory: config/
directoryToSaveModels: manipulation/
directoryToExportModels: output/
pathToProfile: config/smarty.profile.uml
pathToProfileConcern: config/perfilConcerns.profile.uml
pathToProfileRelationships: config/relationships.profile.uml
pathToProfilePatterns: config/patterns.profile.uml